INSERT INTO game_tags(uuid, key, value, game_id)
VALUES
(gen_random_uuid(), 'genre', '4X', (SELECT uuid FROM games where short_url = 'alpha_centauri')),
(gen_random_uuid(), 'artistic', 'sci-fi', (SELECT uuid FROM games where short_url = 'alpha_centauri')),
(gen_random_uuid(), 'extra', 'bestseller', (SELECT uuid FROM games where short_url = 'alpha_centauri')),
(gen_random_uuid(), 'extra', 'game_of_the_year', (SELECT uuid FROM games where short_url = 'alpha_centauri')),
(gen_random_uuid(), 'genre', 'FPS', (SELECT uuid FROM games where short_url = 'killing_time')),
(gen_random_uuid(), 'artistic', 'interwar', (SELECT uuid FROM games where short_url = 'killing_time')),
(gen_random_uuid(), 'genre', 'FPS', (SELECT uuid FROM games where short_url = 'shadow_warrior')),
(gen_random_uuid(), 'artistic', 'contemporary', (SELECT uuid FROM games where short_url = 'shadow_warrior')),
(gen_random_uuid(), 'genre', 'FPS', (SELECT uuid FROM games where short_url = 'quake')),
(gen_random_uuid(), 'artistic', 'cultist', (SELECT uuid FROM games where short_url = 'quake')),
(gen_random_uuid(), 'extra', 'bestseller', (SELECT uuid FROM games where short_url = 'quake')),
(gen_random_uuid(), 'extra', 'revolutionary', (SELECT uuid FROM games where short_url = 'quake')),
(gen_random_uuid(), 'genre', 'RTS', (SELECT uuid FROM games where short_url = 'starcraft')),
(gen_random_uuid(), 'artistic', 'sci-fi', (SELECT uuid FROM games where short_url = 'starcraft')),
(gen_random_uuid(), 'extra', 'bestseller', (SELECT uuid FROM games where short_url = 'starcraft')),
(gen_random_uuid(), 'genre', 'RTS', (SELECT uuid FROM games where short_url = 'redalert')),
(gen_random_uuid(), 'artistic', 'alternative', (SELECT uuid FROM games where short_url = 'redalert')),
(gen_random_uuid(), 'extra', 'bestseller', (SELECT uuid FROM games where short_url = 'redalert')),
(gen_random_uuid(), 'extra', 'game_of_the_year', (SELECT uuid FROM games where short_url = 'redalert'))
